/* C code produced by gperf version 2.7.2 */
/* Command-line: ../src/gperf -L C -F ', 0, 0' -p -j1 -i 1 -g -o -t -G -N is_reserved_word -k'1,3,$'  */

/* Command-line: gperf -L KR-C -F ', 0, 0' -p -j1 -i 1 -g -o -t -N is_reserved_word -k1,3,$ c-parse.gperf  */ 
struct resword { const char *name; short token; enum rid rid; };

#define TOTAL_KEYWORDS 83
#define MIN_WORD_LENGTH 2
#define MAX_WORD_LENGTH 20
#define MIN_HASH_VALUE 12
#define MAX_HASH_VALUE 125
/* maximum key range = 114, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126,  19, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126,   1, 126,  12,  50,  17,
       22,  18,  51,  37,   5,  10, 126,  15,  35,  49,
       27,  40,  28, 126,   2,  20,   1,  33,  64,   7,
       11,   4,   7, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
      126, 126, 126, 126, 126, 126
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[2]];
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

static struct resword wordlist[] =
  {
    {"", 0, 0}, {"", 0, 0}, {"", 0, 0}, {"", 0, 0},
    {"", 0, 0}, {"", 0, 0}, {"", 0, 0}, {"", 0, 0},
    {"", 0, 0}, {"", 0, 0}, {"", 0, 0}, {"", 0, 0},
    {"__real__", REALPART, NORID},
    {"__typeof__", TYPEOF, NORID},
    {"__restrict", TYPE_QUAL, RID_RESTRICT},
    {"int", TYPESPEC, RID_INT},
    {"__restrict__", TYPE_QUAL, RID_RESTRICT},
    {"", 0, 0}, {"", 0, 0}, {"", 0, 0},
    {"__imag__", IMAGPART, NORID},
    {"__asm__", ASM_KEYWORD, NORID},
    {"__inline__", SCSPEC, RID_INLINE},
    {"__iterator", SCSPEC, RID_ITERATOR},
    {"__iterator__", SCSPEC, RID_ITERATOR},
    {"__alignof__", ALIGNOF, NORID},
    {"__const", TYPE_QUAL, RID_CONST},
    {"__attribute__", ATTRIBUTE, NORID},
    {"__const__", TYPE_QUAL, RID_CONST},
    {"struct", STRUCT, NORID},
    {"__complex__", TYPESPEC, RID_COMPLEX},
    {"restrict", TYPE_QUAL, RID_RESTRICT},
    {"__signed__", TYPESPEC, RID_SIGNED},
    {"__extension__", EXTENSION, NORID},
    {"id", OBJECTNAME, RID_ID},
    {"char", TYPESPEC, RID_CHAR},
    {"return", RETURN, NORID},
    {"__inline", SCSPEC, RID_INLINE},
    {"__complex", TYPESPEC, RID_COMPLEX},
    {"in", TYPE_QUAL, RID_IN},
    {"while", WHILE, NORID},
    {"switch", SWITCH, NORID},
    {"__attribute", ATTRIBUTE, NORID},
    {"", 0, 0},
    {"__real", REALPART, NORID},
    {"out", TYPE_QUAL, RID_OUT},
    {"__label__", LABEL, NORID},
    {"@private", PRIVATE, NORID},
    {"@selector", SELECTOR, NORID},
    {"register", SCSPEC, RID_REGISTER},
    {"const", TYPE_QUAL, RID_CONST},
    {"__signed", TYPESPEC, RID_SIGNED},
    {"extern", SCSPEC, RID_EXTERN},
    {"@protected", PROTECTED, NORID},
    {"__imag", IMAGPART, NORID},
    {"static", SCSPEC, RID_STATIC},
    {"inout", TYPE_QUAL, RID_INOUT},
    {"auto", SCSPEC, RID_AUTO},
    {"for", FOR, NORID},
    {"case", CASE, NORID},
    {"else", ELSE, NORID},
    {"__typeof", TYPEOF, NORID},
    {"@defs", DEFS, NORID},
    {"if", IF, NORID},
    {"do", DO, NORID},
    {"@protocol", PROTOCOL, NORID},
    {"short", TYPESPEC, RID_SHORT},
    {"__asm", ASM_KEYWORD, NORID},
    {"oneway", TYPE_QUAL, RID_ONEWAY},
    {"inline", SCSPEC, RID_INLINE},
    {"continue", CONTINUE, NORID},
    {"@encode", ENCODE, NORID},
    {"@end", END, NORID},
    {"__alignof", ALIGNOF, NORID},
    {"@interface", INTERFACE, NORID},
    {"union", UNION, NORID},
    {"@public", PUBLIC, NORID},
    {"bycopy", TYPE_QUAL, RID_BYCOPY},
    {"__volatile__", TYPE_QUAL, RID_VOLATILE},
    {"double", TYPESPEC, RID_DOUBLE},
    {"@class", CLASS, NORID},
    {"default", DEFAULT, NORID},
    {"goto", GOTO, NORID},
    {"unsigned", TYPESPEC, RID_UNSIGNED},
    {"sizeof", SIZEOF, NORID},
    {"signed", TYPESPEC, RID_SIGNED},
    {"typeof", TYPEOF, NORID},
    {"typedef", SCSPEC, RID_TYPEDEF},
    {"break", BREAK, NORID},
    {"", 0, 0}, {"", 0, 0}, {"", 0, 0}, {"", 0, 0},
    {"__volatile", TYPE_QUAL, RID_VOLATILE},
    {"", 0, 0}, {"", 0, 0}, {"", 0, 0},
    {"float", TYPESPEC, RID_FLOAT},
    {"", 0, 0},
    {"@compatibility_alias", ALIAS, NORID},
    {"void", TYPESPEC, RID_VOID},
    {"", 0, 0}, {"", 0, 0},
    {"long", TYPESPEC, RID_LONG},
    {"enum", ENUM, NORID},
    {"", 0, 0}, {"", 0, 0}, {"", 0, 0},
    {"byref", TYPE_QUAL, RID_BYREF},
    {"", 0, 0},
    {"@implementation", IMPLEMENTATION, NORID},
    {"", 0, 0}, {"", 0, 0},
    {"asm", ASM_KEYWORD, NORID},
    {"", 0, 0}, {"", 0, 0}, {"", 0, 0}, {"", 0, 0},
    {"", 0, 0}, {"", 0, 0}, {"", 0, 0}, {"", 0, 0},
    {"", 0, 0}, {"", 0, 0}, {"", 0, 0},
    {"volatile", TYPE_QUAL, RID_VOLATILE}
  };

#ifdef __GNUC__
__inline
#endif
struct resword *
is_reserved_word (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register const char *s = wordlist[key].name;

          if (*str == *s && !strcmp (str + 1, s + 1))
            return &wordlist[key];
        }
    }
  return 0;
}
