/* C code produced by gperf version 2.7.2 */
/* Command-line: ../src/gperf -L C -F ', 0, 0, 0' -D -E -S1 -p -j1 -i 1 -g -o -t -k'*'  */
struct resword {
  const char  *name;
  short        token;
  enum rid     rid;
  enum toktype { RESERVED, DIRECTIVE, PREDEF } flags;
};
extern tree ridpointers [];
/* maximum key range = 2275, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned short asso_values[] =
    {
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291,  300,    9,   14,   11,    1,
        16,  321,    2,   33,  199,    9,    7,   99,   64,   56,
        93,    7,    7,  123,    1,  122,   10,    8,   71,   45,
        26, 2291, 2291, 2291, 2291,    1, 2291,  126,   89,   22,
       204,    1,  230,  158,    1,    7,   71,    2,  125,   17,
         6,   25,   13,    7,    4,   71,    1,  157,   14,  122,
         4,  132,   66, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291, 2291,
      2291, 2291, 2291, 2291, 2291, 2291, 2291
    };
  register int hval = len;

  switch (hval)
    {
      default:
      case 30:
        hval += asso_values[(unsigned char)str[29]];
      case 29:
        hval += asso_values[(unsigned char)str[28]];
      case 28:
        hval += asso_values[(unsigned char)str[27]];
      case 27:
        hval += asso_values[(unsigned char)str[26]];
      case 26:
        hval += asso_values[(unsigned char)str[25]];
      case 25:
        hval += asso_values[(unsigned char)str[24]];
      case 24:
        hval += asso_values[(unsigned char)str[23]];
      case 23:
        hval += asso_values[(unsigned char)str[22]];
      case 22:
        hval += asso_values[(unsigned char)str[21]];
      case 21:
        hval += asso_values[(unsigned char)str[20]];
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      case 19:
        hval += asso_values[(unsigned char)str[18]];
      case 18:
        hval += asso_values[(unsigned char)str[17]];
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      case 16:
        hval += asso_values[(unsigned char)str[15]];
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      case 2:
        hval += asso_values[(unsigned char)str[1]+1];
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

#ifdef __GNUC__
__inline
#endif
struct resword *
in_word_set (str, len)
     register const char *str;
     register unsigned int len;
{
  enum
    {
      TOTAL_KEYWORDS = 300,
      MIN_WORD_LENGTH = 2,
      MAX_WORD_LENGTH = 30,
      MIN_HASH_VALUE = 16,
      MAX_HASH_VALUE = 2290
    };

  static struct resword wordlist[] =
    {
      {"to",			TO,			NORID,	RESERVED},
      {"then",			THEN,			NORID,	RESERVED},
      {"EVER",			EVER,			NORID,	RESERVED},
      {"not",			NOT,			NORID,	RESERVED},
      {"xor",			XOR,			NORID,	RESERVED},
      {"od",			OD,			NORID,	RESERVED},
      {"DCL",			DCL,			NORID,	RESERVED},
      {"in",			IN,			RID_IN,	RESERVED},
      {"FAR",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"BY",			BY,			NORID,	RESERVED},
      {"CALL",			CALL,			NORID,	RESERVED},
      {"REF",			REF,			NORID,	RESERVED},
      {"out",			PARAMATTR,		RID_OUT,	RESERVED},
      {"init",			INIT,			NORID,	RESERVED},
      {"on",			ON,			NORID,	RESERVED},
      {"context",		CONTEXT,		NORID,	RESERVED},
      {"OD",			OD,			NORID,	RESERVED},
      {"BUFFER",			BUFFER,			NORID,	RESERVED},
      {"CYCLE",			CYCLE,			NORID,	RESERVED},
      {"OUT",			PARAMATTR,		RID_OUT,	RESERVED},
      {"END",			END,			NORID,	RESERVED},
      {"EVEN",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"EVENT",			EVENT,			NORID,	RESERVED},
      {"EXIT",			EXIT,			NORID,	RESERVED},
      {"WHILE",			WHILE,			NORID,	RESERVED},
      {"RECEIVE",		RECEIVE,		NORID,	RESERVED},
      {"this",			THIS,			NORID,	RESERVED},
      {"IN",			IN,			RID_IN,	RESERVED},
      {"TEXT",			TEXT,			NORID,	RESERVED},
      {"else",			ELSE,			NORID,	RESERVED},
      {"TO",			TO,			NORID,	RESERVED},
      {"or",			OR,			NORID,	RESERVED},
      {"pos",			POS,			NORID,	RESERVED},
      {"THEN",			THEN,			NORID,	RESERVED},
      {"spec",			SPEC,			NORID,	RESERVED},
      {"DO",			DO,			NORID,	RESERVED},
      {"ROW",			ROW,			NORID,	RESERVED},
      {"ON",			ON,			NORID,	RESERVED},
      {"LOC",			LOC,			NORID,	RESERVED},
      {"FOR",			FOR,			NORID,	RESERVED},
      {"REM",			REM,			NORID,	RESERVED},
      {"INIT",			INIT,			NORID,	RESERVED},
      {"PACK",			PACK,			NORID,	RESERVED},
      {"pack",			PACK,			NORID,	RESERVED},
      {"UP",			UP,			NORID,	RESERVED},
      {"ever",			EVER,			NORID,	RESERVED},
      {"even",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"proc",			PROC,			NORID,	RESERVED},
      {"event",			EVENT,			NORID,	RESERVED},
      {"optimize",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"row",			ROW,			NORID,	RESERVED},
      {"SET",			SET,			NORID,	RESERVED},
      {"exit",			EXIT,			NORID,	RESERVED},
      {"syn",			SYN,			NORID,	RESERVED},
      {"asm",			ASM_KEYWORD,		NORID,	RESERVED},
      {"SPEC",			SPEC,			NORID,	RESERVED},
      {"CASE",			CASE,			NORID,	RESERVED},
      {"BUFFER_CODE",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"esac",			ESAC,			NORID,	RESERVED},
      {"by",			BY,			NORID,	RESERVED},
      {"BASED",			BASED,			NORID,	RESERVED},
      {"NOT",			NOT,			NORID,	RESERVED},
      {"BODY",			BODY,			NORID,	RESERVED},
      {"loc",			LOC,			NORID,	RESERVED},
      {"bit",			BOOLS,			RID_BOOLS,	PREDEF},
      {"up",			UP,			NORID,	RESERVED},
      {"if",			IF,			NORID,	RESERVED},
      {"EVENT_CODE",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"bin",			BIN,			NORID,	RESERVED},
      {"XOR",			XOR,			NORID,	RESERVED},
      {"FORBID",			FORBID,			NORID,	RESERVED},
      {"inline",			INLINE,			RID_INLINE,	RESERVED},
      {"DOWN",			DOWN,			NORID,	RESERVED},
      {"OR",			OR,			NORID,	RESERVED},
      {"of",			OF,			NORID,	RESERVED},
      {"REMOTE",			REMOTE,			NORID,	RESERVED},
      {"case",			CASE,			NORID,	RESERVED},
      {"nopack",			NOPACK,			NORID,	RESERVED},
      {"empty_on",		EMPTY_ON,		NORID,	DIRECTIVE},
      {"THIS",			THIS,			NORID,	RESERVED},
      {"with",			WITH,			NORID,	RESERVED},
      {"INLINE",			INLINE,			RID_INLINE,	RESERVED},
      {"goto",			GOTO,			NORID,	RESERVED},
      {"SEIZE",			SEIZE,			NORID,	RESERVED},
      {"MOD",			MOD,			NORID,	RESERVED},
      {"assert",			ASSERT,			NORID,	RESERVED},
      {"BIT",			BOOLS,			RID_BOOLS,	PREDEF},
      {"WITH",			WITH,			NORID,	RESERVED},
      {"SYN",			SYN,			NORID,	RESERVED},
      {"FI",			FI,			NORID,	RESERVED},
      {"SEND",			SEND,			NORID,	RESERVED},
      {"do",			DO,			NORID,	RESERVED},
      {"inout",			PARAMATTR,		RID_INOUT,	RESERVED},
      {"continue",		CONTINUE,		NORID,	RESERVED},
      {"RETURN",			RETURN,			NORID,	RESERVED},
      {"ELSE",			ELSE,			NORID,	RESERVED},
      {"nolist",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ORIF",			ORIF,			NORID,	RESERVED},
      {"end",			END,			NORID,	RESERVED},
      {"powerset",		POWERSET,		NORID,	RESERVED},
      {"chars",			CHARS,			NORID,	RESERVED},
      {"mod",			MOD,			NORID,	RESERVED},
      {"text",			TEXT,			NORID,	RESERVED},
      {"cycle",			CYCLE,			NORID,	RESERVED},
      {"step",			STEP,			NORID,	RESERVED},
      {"CCITT_OS",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"for",			FOR,			NORID,	RESERVED},
      {"NONREF",			NONREF,			NORID,	RESERVED},
      {"CONTEXT",		CONTEXT,		NORID,	RESERVED},
      {"rem",			REM,			NORID,	RESERVED},
      {"NEWMODE",		NEWMODE,		NORID,	RESERVED},
      {"range",			RANGE,			NORID,	RESERVED},
      {"OPTIMIZE",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"page",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"nonref",			NONREF,			NORID,	RESERVED},
      {"while",			WHILE,			NORID,	RESERVED},
      {"priority",		PRIORITY,		NORID,	RESERVED},
      {"stop",			STOP,			NORID,	RESERVED},
      {"all",			ALL,			NORID,	RESERVED},
      {"list",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"INOUT",			PARAMATTR,		RID_INOUT,	RESERVED},
      {"CAUSE",			CAUSE,			NORID,	RESERVED},
      {"BIN",			BIN,			NORID,	RESERVED},
      {"ELSIF",			ELSIF,			NORID,	RESERVED},
      {"timeout",		TIMEOUT,		NORID,	RESERVED},
      {"process",		PROCESS,		NORID,	RESERVED},
      {"RESULT",			RESULT,			NORID,	RESERVED},
      {"remote",			REMOTE,			NORID,	RESERVED},
      {"at",			AT,			NORID,	RESERVED},
      {"receive",		RECEIVE,		NORID,	RESERVED},
      {"exceptions",		EXCEPTIONS,		NORID,	RESERVED},
      {"PROC",			PROC,			NORID,	RESERVED},
      {"BOOLS",			BOOLS,			RID_BOOLS,	RESERVED},
      {"after",			AFTER,			NORID,	RESERVED},
      {"range_on",		RANGE_ON,		NORID,	DIRECTIVE},
      {"EMPTY_OFF",		EMPTY_OFF,		NORID,	DIRECTIVE},
      {"fi",			FI,			NORID,	RESERVED},
      {"simple",			SIMPLE,			NORID,	RESERVED},
      {"set",			SET,			NORID,	RESERVED},
      {"POS",			POS,			NORID,	RESERVED},
      {"ESAC",			ESAC,			NORID,	RESERVED},
      {"far",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"NOLIST",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"bools",			BOOLS,			RID_BOOLS,	RESERVED},
      {"elsif",			ELSIF,			NORID,	RESERVED},
      {"EMPTY_ON",		EMPTY_ON,		NORID,	DIRECTIVE},
      {"LIST",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"POWERSET",		POWERSET,		NORID,	RESERVED},
      {"orif",			ORIF,			NORID,	RESERVED},
      {"READ",			READ,			RID_READ,	RESERVED},
      {"MODULE",			MODULE,			NORID,	RESERVED},
      {"ccitt_os",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"optimize_runtime",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"RECURSIVE",		RECURSIVE,		NORID,	RESERVED},
      {"STEP",			STEP,			NORID,	RESERVED},
      {"cause",			CAUSE,			NORID,	RESERVED},
      {"RETURNS",		RETURNS,		NORID,	RESERVED},
      {"down",			DOWN,			NORID,	RESERVED},
      {"LARGE",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"IF",			IF,			NORID,	RESERVED},
      {"PREFIXED",		PREFIXED,		NORID,	RESERVED},
      {"and",			AND,			NORID,	RESERVED},
      {"start",			START,			NORID,	RESERVED},
      {"call",			CALL,			NORID,	RESERVED},
      {"grant",			GRANT,			NORID,	RESERVED},
      {"AND",			AND,			NORID,	RESERVED},
      {"OF",			OF,			NORID,	RESERVED},
      {"seize",			SEIZE,			NORID,	RESERVED},
      {"USE_SEIZE_FILE",		USE_SEIZE_FILE,		NORID,	DIRECTIVE},
      {"large",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"DELAY",			DELAY,			NORID,	RESERVED},
      {"MEDIUM",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"SYNMODE",		SYNMODE,		NORID,	RESERVED},
      {"reentrant",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"print_o_code",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"static",			STATIC,			NORID,	RESERVED},
      {"no_overlap_check",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"event_code",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"STRUCT",			STRUCT,			NORID,	RESERVED},
      {"synmode",		SYNMODE,		NORID,	RESERVED},
      {"STOP",			STOP,			NORID,	RESERVED},
      {"PRIORITY",		PRIORITY,		NORID,	RESERVED},
      {"CONTINUE",		CONTINUE,		NORID,	RESERVED},
      {"ASM",			ASM_KEYWORD,		NORID,	RESERVED},
      {"RANGE",			RANGE,			NORID,	RESERVED},
      {"return",			RETURN,			NORID,	RESERVED},
      {"ALL",			ALL,			NORID,	RESERVED},
      {"varying",		VARYING,		NORID,	RESERVED},
      {"struct",			STRUCT,			NORID,	RESERVED},
      {"ANDIF",			ANDIF,			NORID,	RESERVED},
      {"AT",			AT,			NORID,	RESERVED},
      {"PAGE",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"process_type",		PROCESS_TYPE_TOKEN,	NORID,	DIRECTIVE},
      {"region",			REGION,			NORID,	RESERVED},
      {"ASSERT",			ASSERT,			NORID,	RESERVED},
      {"EXCEPTIONS",		EXCEPTIONS,		NORID,	RESERVED},
      {"body",			BODY,			NORID,	RESERVED},
      {"BEGIN",			BEGINTOKEN,		NORID,	RESERVED},
      {"dynamic",		DYNAMIC,		RID_DYNAMIC,	RESERVED},
      {"small",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"based",			BASED,			NORID,	RESERVED},
      {"array",			ARRAY,			NORID,	RESERVED},
      {"PRINT_O_CODE",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ref",			REF,			NORID,	RESERVED},
      {"REENTRANT",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"GOTO",			GOTO,			NORID,	RESERVED},
      {"returns",		RETURNS,		NORID,	RESERVED},
      {"CHARS",			CHARS,			NORID,	RESERVED},
      {"TIMEOUT",		TIMEOUT,		NORID,	RESERVED},
      {"begin",			BEGINTOKEN,		NORID,	RESERVED},
      {"VARYING",		VARYING,		NORID,	RESERVED},
      {"RANGE_OFF",		RANGE_OFF,		NORID,	DIRECTIVE},
      {"access",			ACCESS,			NORID,	RESERVED},
      {"REGION",			REGION,			NORID,	RESERVED},
      {"SMALL",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"send",			SEND,			NORID,	RESERVED},
      {"recursive",		RECURSIVE,		NORID,	RESERVED},
      {"module",			MODULE,			NORID,	RESERVED},
      {"SIMPLE",			SIMPLE,			NORID,	RESERVED},
      {"RANGE_ON",		RANGE_ON,		NORID,	DIRECTIVE},
      {"dcl",			DCL,			NORID,	RESERVED},
      {"prefixed",		PREFIXED,		NORID,	RESERVED},
      {"PROCESS",		PROCESS,		NORID,	RESERVED},
      {"all_static_on",		ALL_STATIC_ON,		NORID,	DIRECTIVE},
      {"forbid",			FORBID,			NORID,	RESERVED},
      {"DYNAMIC",		DYNAMIC,		RID_DYNAMIC,	RESERVED},
      {"START",			START,			NORID,	RESERVED},
      {"signal",			SIGNAL,			NORID,	RESERVED},
      {"read",			READ,			RID_READ,	RESERVED},
      {"state_routine",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"buffer",			BUFFER,			NORID,	RESERVED},
      {"ACCESS",			ACCESS,			NORID,	RESERVED},
      {"NOPACK",			NOPACK,			NORID,	RESERVED},
      {"USE_SEIZE_FILE_RESTRICTED",	USE_SEIZE_FILE_RESTRICTED,	NORID,	DIRECTIVE},
      {"result",			RESULT,			NORID,	RESERVED},
      {"andif",			ANDIF,			NORID,	RESERVED},
      {"STATIC",			STATIC,			NORID,	RESERVED},
      {"OPTIMIZE_RUNTIME",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"newmode",		NEWMODE,		NORID,	RESERVED},
      {"short_pred_succ",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"SHORT_PRED_SUCC",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"AFTER",			AFTER,			NORID,	RESERVED},
      {"extra_const_seg",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"medium",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"empty_off",		EMPTY_OFF,		NORID,	DIRECTIVE},
      {"general",		GENERAL,		NORID,	RESERVED},
      {"use_seize_file",		USE_SEIZE_FILE,		NORID,	DIRECTIVE},
      {"PROCESS_TYPE",		PROCESS_TYPE_TOKEN,	NORID,	DIRECTIVE},
      {"NO_OVERLAP_CHECK",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"DEBUG_LINES",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"GENERAL",		GENERAL,		NORID,	RESERVED},
      {"multiple_const_segs",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"range_off",		RANGE_OFF,		NORID,	DIRECTIVE},
      {"DEBUG_TYPES",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"reentrant_all",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ARRAY",			ARRAY,			NORID,	RESERVED},
      {"REENTRANT_ALL",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"optimization_window",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"GRANT",			GRANT,			NORID,	RESERVED},
      {"signal_code",		SIGNAL_CODE,		NORID,	DIRECTIVE},
      {"delay",			DELAY,			NORID,	RESERVED},
      {"buffer_code",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"generate_set_names",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"STATE_ROUTINE",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"only_for_target",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"grant_file_size",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ONLY_FOR_TARGET",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"OPTIMIZATION_WINDOW",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"print_symbol_table",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"DEBUG_SYMBOLS",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ALL_STATIC_OFF",		ALL_STATIC_OFF,		NORID,  DIRECTIVE},
      {"PRINT_SYMBOL_TABLE",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"all_static_off",		ALL_STATIC_OFF,		NORID,  DIRECTIVE},
      {"use_seize_file_restricted",	USE_SEIZE_FILE_RESTRICTED,	NORID,	DIRECTIVE},
      {"ALL_STATIC_ON",		ALL_STATIC_ON,		NORID,	DIRECTIVE},
      {"signal_max_length",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"SIGNAL",			SIGNAL,			NORID,	RESERVED},
      {"debug_lines",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"GRANT_FILE_SIZE",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"debug_types",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"EXTRA_CONST_SEG",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"multiple_data_segs",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"MULTIPLE_CONST_SEGS",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ONLY_FOR_SIMULATION",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"SIGNAL_CODE",		SIGNAL_CODE,		NORID,	DIRECTIVE},
      {"only_for_simulation",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"SEND_BUFFER_DEFAULT_PRIORITY",	SEND_BUFFER_DEFAULT_PRIORITY,	NORID,	DIRECTIVE},
      {"MAKE_PUBLICS_FOR_DISCRETE_SYNS",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"generate_all_set_names",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"debug_symbols",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"support_causing_address",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"GENERATE_SET_NAMES",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"MULTIPLE_DATA_SEGS",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"make_publics_for_discrete_syns",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"GENERATE_ALL_SET_NAMES",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"SEND_SIGNAL_DEFAULT_PRIORITY",	SEND_SIGNAL_DEFAULT_PRIORITY,	NORID,	DIRECTIVE},
      {"SIGNAL_MAX_LENGTH",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"SUPPORT_CAUSING_ADDRESS",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"send_signal_default_priority",	SEND_SIGNAL_DEFAULT_PRIORITY,	NORID,	DIRECTIVE},
      {"send_buffer_default_priority",	SEND_BUFFER_DEFAULT_PRIORITY,	NORID,	DIRECTIVE}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          register struct resword *wordptr;
          register struct resword *wordendptr;
          register struct resword *resword;

          switch (key - 16)
            {
              case 0:
                resword = &wordlist[0];
                goto compare;
              case 3:
                resword = &wordlist[1];
                goto compare;
              case 5:
                resword = &wordlist[2];
                goto compare;
              case 7:
                resword = &wordlist[3];
                goto compare;
              case 8:
                resword = &wordlist[4];
                goto compare;
              case 12:
                resword = &wordlist[5];
                goto compare;
              case 16:
                resword = &wordlist[6];
                goto compare;
              case 18:
                resword = &wordlist[7];
                goto compare;
              case 19:
                resword = &wordlist[8];
                goto compare;
              case 21:
                resword = &wordlist[9];
                goto compare;
              case 25:
                resword = &wordlist[10];
                goto compare;
              case 26:
                resword = &wordlist[11];
                goto compare;
              case 27:
                resword = &wordlist[12];
                goto compare;
              case 28:
                resword = &wordlist[13];
                goto compare;
              case 36:
                resword = &wordlist[14];
                goto compare;
              case 39:
                resword = &wordlist[15];
                goto compare;
              case 43:
                resword = &wordlist[16];
                goto compare;
              case 49:
                resword = &wordlist[17];
                goto compare;
              case 51:
                resword = &wordlist[18];
                goto compare;
              case 54:
                resword = &wordlist[19];
                goto compare;
              case 55:
                resword = &wordlist[20];
                goto compare;
              case 62:
                resword = &wordlist[21];
                goto compare;
              case 64:
                resword = &wordlist[22];
                goto compare;
              case 68:
                resword = &wordlist[23];
                goto compare;
              case 71:
                resword = &wordlist[24];
                goto compare;
              case 73:
                resword = &wordlist[25];
                goto compare;
              case 74:
                resword = &wordlist[26];
                goto compare;
              case 75:
                resword = &wordlist[27];
                goto compare;
              case 77:
                resword = &wordlist[28];
                goto compare;
              case 78:
                resword = &wordlist[29];
                goto compare;
              case 80:
                resword = &wordlist[30];
                goto compare;
              case 82:
                resword = &wordlist[31];
                goto compare;
              case 84:
                resword = &wordlist[32];
                goto compare;
              case 87:
                resword = &wordlist[33];
                goto compare;
              case 89:
                resword = &wordlist[34];
                goto compare;
              case 90:
                resword = &wordlist[35];
                goto compare;
              case 95:
                resword = &wordlist[36];
                goto compare;
              case 98:
                resword = &wordlist[37];
                goto compare;
              case 101:
                resword = &wordlist[38];
                goto compare;
              case 103:
                resword = &wordlist[39];
                goto compare;
              case 109:
                resword = &wordlist[40];
                goto compare;
              case 111:
                resword = &wordlist[41];
                goto compare;
              case 113:
                resword = &wordlist[42];
                goto compare;
              case 114:
                resword = &wordlist[43];
                goto compare;
              case 115:
                resword = &wordlist[44];
                goto compare;
              case 116:
                resword = &wordlist[45];
                goto compare;
              case 118:
                resword = &wordlist[46];
                goto compare;
              case 119:
                resword = &wordlist[47];
                goto compare;
              case 120:
                resword = &wordlist[48];
                goto compare;
              case 123:
                resword = &wordlist[49];
                goto compare;
              case 126:
                resword = &wordlist[50];
                goto compare;
              case 127:
                resword = &wordlist[51];
                goto compare;
              case 129:
                resword = &wordlist[52];
                goto compare;
              case 130:
                resword = &wordlist[53];
                goto compare;
              case 131:
                resword = &wordlist[54];
                goto compare;
              case 133:
                resword = &wordlist[55];
                goto compare;
              case 135:
                resword = &wordlist[56];
                goto compare;
              case 137:
                resword = &wordlist[57];
                goto compare;
              case 138:
                resword = &wordlist[58];
                goto compare;
              case 141:
                resword = &wordlist[59];
                goto compare;
              case 142:
                resword = &wordlist[60];
                goto compare;
              case 145:
                resword = &wordlist[61];
                goto compare;
              case 146:
                resword = &wordlist[62];
                goto compare;
              case 147:
                resword = &wordlist[63];
                goto compare;
              case 148:
                resword = &wordlist[64];
                goto compare;
              case 150:
                resword = &wordlist[65];
                goto compare;
              case 151:
                resword = &wordlist[66];
                goto compare;
              case 152:
                resword = &wordlist[67];
                goto compare;
              case 153:
                resword = &wordlist[68];
                goto compare;
              case 158:
                resword = &wordlist[69];
                goto compare;
              case 159:
                resword = &wordlist[70];
                goto compare;
              case 161:
                resword = &wordlist[71];
                goto compare;
              case 164:
                resword = &wordlist[72];
                goto compare;
              case 165:
                resword = &wordlist[73];
                goto compare;
              case 169:
                resword = &wordlist[74];
                goto compare;
              case 170:
                resword = &wordlist[75];
                goto compare;
              case 171:
                resword = &wordlist[76];
                goto compare;
              case 172:
                resword = &wordlist[77];
                goto compare;
              case 177:
                resword = &wordlist[78];
                goto compare;
              case 178:
                resword = &wordlist[79];
                goto compare;
              case 183:
                resword = &wordlist[80];
                goto compare;
              case 184:
                resword = &wordlist[81];
                goto compare;
              case 185:
                resword = &wordlist[82];
                goto compare;
              case 188:
                resword = &wordlist[83];
                goto compare;
              case 190:
                resword = &wordlist[84];
                goto compare;
              case 194:
                resword = &wordlist[85];
                goto compare;
              case 196:
                resword = &wordlist[86];
                goto compare;
              case 198:
                resword = &wordlist[87];
                goto compare;
              case 200:
                resword = &wordlist[88];
                goto compare;
              case 201:
                resword = &wordlist[89];
                goto compare;
              case 202:
                resword = &wordlist[90];
                goto compare;
              case 203:
                resword = &wordlist[91];
                goto compare;
              case 204:
                resword = &wordlist[92];
                goto compare;
              case 205:
                resword = &wordlist[93];
                goto compare;
              case 207:
                resword = &wordlist[94];
                goto compare;
              case 212:
                resword = &wordlist[95];
                goto compare;
              case 213:
                resword = &wordlist[96];
                goto compare;
              case 216:
                resword = &wordlist[97];
                goto compare;
              case 217:
                resword = &wordlist[98];
                goto compare;
              case 218:
                resword = &wordlist[99];
                goto compare;
              case 219:
                resword = &wordlist[100];
                goto compare;
              case 221:
                resword = &wordlist[101];
                goto compare;
              case 224:
                resword = &wordlist[102];
                goto compare;
              case 225:
                resword = &wordlist[103];
                goto compare;
              case 230:
                resword = &wordlist[104];
                goto compare;
              case 232:
                resword = &wordlist[105];
                goto compare;
              case 234:
                resword = &wordlist[106];
                goto compare;
              case 235:
                resword = &wordlist[107];
                goto compare;
              case 236:
                resword = &wordlist[108];
                goto compare;
              case 238:
                resword = &wordlist[109];
                goto compare;
              case 246:
                resword = &wordlist[110];
                goto compare;
              case 247:
                resword = &wordlist[111];
                goto compare;
              case 248:
                resword = &wordlist[112];
                goto compare;
              case 249:
                resword = &wordlist[113];
                goto compare;
              case 250:
                resword = &wordlist[114];
                goto compare;
              case 251:
                resword = &wordlist[115];
                goto compare;
              case 252:
                resword = &wordlist[116];
                goto compare;
              case 254:
                resword = &wordlist[117];
                goto compare;
              case 255:
                resword = &wordlist[118];
                goto compare;
              case 256:
                resword = &wordlist[119];
                goto compare;
              case 257:
                resword = &wordlist[120];
                goto compare;
              case 258:
                resword = &wordlist[121];
                goto compare;
              case 259:
                resword = &wordlist[122];
                goto compare;
              case 261:
                resword = &wordlist[123];
                goto compare;
              case 264:
                resword = &wordlist[124];
                goto compare;
              case 265:
                resword = &wordlist[125];
                goto compare;
              case 266:
                resword = &wordlist[126];
                goto compare;
              case 268:
                resword = &wordlist[127];
                goto compare;
              case 269:
                resword = &wordlist[128];
                goto compare;
              case 270:
                resword = &wordlist[129];
                goto compare;
              case 273:
                resword = &wordlist[130];
                goto compare;
              case 274:
                resword = &wordlist[131];
                goto compare;
              case 277:
                resword = &wordlist[132];
                goto compare;
              case 279:
                resword = &wordlist[133];
                goto compare;
              case 282:
                resword = &wordlist[134];
                goto compare;
              case 286:
                resword = &wordlist[135];
                goto compare;
              case 287:
                resword = &wordlist[136];
                goto compare;
              case 288:
                resword = &wordlist[137];
                goto compare;
              case 289:
                resword = &wordlist[138];
                goto compare;
              case 296:
                resword = &wordlist[139];
                goto compare;
              case 304:
                resword = &wordlist[140];
                goto compare;
              case 310:
                resword = &wordlist[141];
                goto compare;
              case 311:
                resword = &wordlist[142];
                goto compare;
              case 312:
                resword = &wordlist[143];
                goto compare;
              case 315:
                resword = &wordlist[144];
                goto compare;
              case 317:
                resword = &wordlist[145];
                goto compare;
              case 318:
                resword = &wordlist[146];
                goto compare;
              case 319:
                resword = &wordlist[147];
                goto compare;
              case 321:
                resword = &wordlist[148];
                goto compare;
              case 322:
                resword = &wordlist[149];
                goto compare;
              case 323:
                resword = &wordlist[150];
                goto compare;
              case 324:
                resword = &wordlist[151];
                goto compare;
              case 325:
                resword = &wordlist[152];
                goto compare;
              case 326:
                resword = &wordlist[153];
                goto compare;
              case 327:
                resword = &wordlist[154];
                goto compare;
              case 329:
                resword = &wordlist[155];
                goto compare;
              case 331:
                resword = &wordlist[156];
                goto compare;
              case 333:
                resword = &wordlist[157];
                goto compare;
              case 334:
                resword = &wordlist[158];
                goto compare;
              case 340:
                resword = &wordlist[159];
                goto compare;
              case 341:
                resword = &wordlist[160];
                goto compare;
              case 342:
                resword = &wordlist[161];
                goto compare;
              case 348:
                resword = &wordlist[162];
                goto compare;
              case 349:
                resword = &wordlist[163];
                goto compare;
              case 351:
                resword = &wordlist[164];
                goto compare;
              case 354:
                resword = &wordlist[165];
                goto compare;
              case 363:
                resword = &wordlist[166];
                goto compare;
              case 364:
                resword = &wordlist[167];
                goto compare;
              case 365:
                resword = &wordlist[168];
                goto compare;
              case 366:
                resword = &wordlist[169];
                goto compare;
              case 368:
                resword = &wordlist[170];
                goto compare;
              case 370:
                resword = &wordlist[171];
                goto compare;
              case 371:
                resword = &wordlist[172];
                goto compare;
              case 372:
                resword = &wordlist[173];
                goto compare;
              case 373:
                resword = &wordlist[174];
                goto compare;
              case 374:
                resword = &wordlist[175];
                goto compare;
              case 377:
                resword = &wordlist[176];
                goto compare;
              case 378:
                resword = &wordlist[177];
                goto compare;
              case 379:
                resword = &wordlist[178];
                goto compare;
              case 381:
                resword = &wordlist[179];
                goto compare;
              case 382:
                resword = &wordlist[180];
                goto compare;
              case 383:
                resword = &wordlist[181];
                goto compare;
              case 384:
                resword = &wordlist[182];
                goto compare;
              case 387:
                resword = &wordlist[183];
                goto compare;
              case 391:
                resword = &wordlist[184];
                goto compare;
              case 392:
                resword = &wordlist[185];
                goto compare;
              case 393:
                resword = &wordlist[186];
                goto compare;
              case 401:
                resword = &wordlist[187];
                goto compare;
              case 402:
                resword = &wordlist[188];
                goto compare;
              case 405:
                resword = &wordlist[189];
                goto compare;
              case 408:
                resword = &wordlist[190];
                goto compare;
              case 412:
                resword = &wordlist[191];
                goto compare;
              case 418:
                resword = &wordlist[192];
                goto compare;
              case 420:
                resword = &wordlist[193];
                goto compare;
              case 423:
                resword = &wordlist[194];
                goto compare;
              case 425:
                resword = &wordlist[195];
                goto compare;
              case 426:
                resword = &wordlist[196];
                goto compare;
              case 432:
                resword = &wordlist[197];
                goto compare;
              case 439:
                resword = &wordlist[198];
                goto compare;
              case 442:
                resword = &wordlist[199];
                goto compare;
              case 443:
                resword = &wordlist[200];
                goto compare;
              case 448:
                resword = &wordlist[201];
                goto compare;
              case 450:
                resword = &wordlist[202];
                goto compare;
              case 451:
                resword = &wordlist[203];
                goto compare;
              case 454:
                resword = &wordlist[204];
                goto compare;
              case 459:
                resword = &wordlist[205];
                goto compare;
              case 464:
                resword = &wordlist[206];
                goto compare;
              case 466:
                resword = &wordlist[207];
                goto compare;
              case 470:
                resword = &wordlist[208];
                goto compare;
              case 479:
                resword = &wordlist[209];
                goto compare;
              case 480:
                resword = &wordlist[210];
                goto compare;
              case 484:
                resword = &wordlist[211];
                goto compare;
              case 485:
                resword = &wordlist[212];
                goto compare;
              case 487:
                resword = &wordlist[213];
                goto compare;
              case 490:
                resword = &wordlist[214];
                goto compare;
              case 499:
                resword = &wordlist[215];
                goto compare;
              case 503:
                resword = &wordlist[216];
                goto compare;
              case 507:
                resword = &wordlist[217];
                goto compare;
              case 512:
                resword = &wordlist[218];
                goto compare;
              case 515:
                resword = &wordlist[219];
                goto compare;
              case 520:
                resword = &wordlist[220];
                goto compare;
              case 523:
                resword = &wordlist[221];
                goto compare;
              case 524:
                resword = &wordlist[222];
                goto compare;
              case 526:
                resword = &wordlist[223];
                goto compare;
              case 537:
                resword = &wordlist[224];
                goto compare;
              case 538:
                resword = &wordlist[225];
                goto compare;
              case 542:
                resword = &wordlist[226];
                goto compare;
              case 547:
                resword = &wordlist[227];
                goto compare;
              case 552:
                resword = &wordlist[228];
                goto compare;
              case 555:
                resword = &wordlist[229];
                goto compare;
              case 558:
                resword = &wordlist[230];
                goto compare;
              case 562:
                resword = &wordlist[231];
                goto compare;
              case 563:
                resword = &wordlist[232];
                goto compare;
              case 576:
                resword = &wordlist[233];
                goto compare;
              case 578:
                resword = &wordlist[234];
                goto compare;
              case 581:
                resword = &wordlist[235];
                goto compare;
              case 583:
                resword = &wordlist[236];
                goto compare;
              case 584:
                resword = &wordlist[237];
                goto compare;
              case 596:
                resword = &wordlist[238];
                goto compare;
              case 603:
                resword = &wordlist[239];
                goto compare;
              case 606:
                resword = &wordlist[240];
                goto compare;
              case 619:
                resword = &wordlist[241];
                goto compare;
              case 620:
                resword = &wordlist[242];
                goto compare;
              case 622:
                resword = &wordlist[243];
                goto compare;
              case 632:
                resword = &wordlist[244];
                goto compare;
              case 641:
                resword = &wordlist[245];
                goto compare;
              case 668:
                resword = &wordlist[246];
                goto compare;
              case 670:
                resword = &wordlist[247];
                goto compare;
              case 673:
                resword = &wordlist[248];
                goto compare;
              case 703:
                resword = &wordlist[249];
                goto compare;
              case 707:
                resword = &wordlist[250];
                goto compare;
              case 734:
                resword = &wordlist[251];
                goto compare;
              case 737:
                resword = &wordlist[252];
                goto compare;
              case 738:
                resword = &wordlist[253];
                goto compare;
              case 753:
                resword = &wordlist[254];
                goto compare;
              case 764:
                resword = &wordlist[255];
                goto compare;
              case 773:
                resword = &wordlist[256];
                goto compare;
              case 785:
                resword = &wordlist[257];
                goto compare;
              case 798:
                resword = &wordlist[258];
                goto compare;
              case 805:
                resword = &wordlist[259];
                goto compare;
              case 806:
                resword = &wordlist[260];
                goto compare;
              case 816:
                resword = &wordlist[261];
                goto compare;
              case 825:
                resword = &wordlist[262];
                goto compare;
              case 829:
                resword = &wordlist[263];
                goto compare;
              case 858:
                resword = &wordlist[264];
                goto compare;
              case 871:
                resword = &wordlist[265];
                goto compare;
              case 875:
                resword = &wordlist[266];
                goto compare;
              case 893:
                resword = &wordlist[267];
                goto compare;
              case 903:
                resword = &wordlist[268];
                goto compare;
              case 939:
                resword = &wordlist[269];
                goto compare;
              case 966:
                resword = &wordlist[270];
                goto compare;
              case 975:
                resword = &wordlist[271];
                goto compare;
              case 981:
                resword = &wordlist[272];
                goto compare;
              case 996:
                resword = &wordlist[273];
                goto compare;
              case 997:
                resword = &wordlist[274];
                goto compare;
              case 999:
                resword = &wordlist[275];
                goto compare;
              case 1004:
                resword = &wordlist[276];
                goto compare;
              case 1044:
                resword = &wordlist[277];
                goto compare;
              case 1050:
                resword = &wordlist[278];
                goto compare;
              case 1052:
                resword = &wordlist[279];
                goto compare;
              case 1058:
                resword = &wordlist[280];
                goto compare;
              case 1065:
                resword = &wordlist[281];
                goto compare;
              case 1082:
                resword = &wordlist[282];
                goto compare;
              case 1086:
                resword = &wordlist[283];
                goto compare;
              case 1092:
                resword = &wordlist[284];
                goto compare;
              case 1113:
                resword = &wordlist[285];
                goto compare;
              case 1133:
                resword = &wordlist[286];
                goto compare;
              case 1162:
                resword = &wordlist[287];
                goto compare;
              case 1206:
                resword = &wordlist[288];
                goto compare;
              case 1366:
                resword = &wordlist[289];
                goto compare;
              case 1378:
                resword = &wordlist[290];
                goto compare;
              case 1427:
                resword = &wordlist[291];
                goto compare;
              case 1435:
                resword = &wordlist[292];
                goto compare;
              case 1461:
                resword = &wordlist[293];
                goto compare;
              case 1746:
                resword = &wordlist[294];
                goto compare;
              case 1810:
                resword = &wordlist[295];
                goto compare;
              case 1883:
                resword = &wordlist[296];
                goto compare;
              case 1945:
                resword = &wordlist[297];
                goto compare;
              case 2056:
                resword = &wordlist[298];
                goto compare;
              case 2274:
                resword = &wordlist[299];
                goto compare;
            }
          return 0;
        multicompare:
          while (wordptr < wordendptr)
            {
              register const char *s = wordptr->name;

              if (*str == *s && !strcmp (str + 1, s + 1))
                return wordptr;
              wordptr++;
            }
          return 0;
        compare:
          {
            register const char *s = resword->name;

            if (*str == *s && !strcmp (str + 1, s + 1))
              return resword;
          }
        }
    }
  return 0;
}
