/* C code produced by gperf version 2.7.2 */
/* Command-line: ../src/gperf -L C -F ', 0, 0, 0' -D -E -S1 -p -j1 -i 1 -g -o -t -k'*'  */
struct resword {
  const char  *name;
  short        token;
  enum rid     rid;
  enum toktype { RESERVED, DIRECTIVE, PREDEF } flags;
};
extern tree ridpointers [];
/* maximum key range = 2652, duplicates = 6 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned short asso_values[] =
    {
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692,  141,   74,   44,  107,    1,
       208,    1,    1,   22, 2692,    4,   43,  195,  151,   67,
        60, 2692,   64,   11,  452,   42,   11,    2,    3,   48,
         8, 2692, 2692, 2692, 2692,    1, 2692,    6,   52,   37,
        93,    1,   78,    1,   15,    7, 2692,    2,  119,   52,
       345,  231,   33, 2692,   92,    1,  233,   60,    1,    2,
         1,   80,   25, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692, 2692,
      2692, 2692, 2692, 2692, 2692, 2692
    };
  register int hval = len;

  switch (hval)
    {
      default:
      case 30:
        hval += asso_values[(unsigned char)str[29]];
      case 29:
        hval += asso_values[(unsigned char)str[28]];
      case 28:
        hval += asso_values[(unsigned char)str[27]];
      case 27:
        hval += asso_values[(unsigned char)str[26]];
      case 26:
        hval += asso_values[(unsigned char)str[25]];
      case 25:
        hval += asso_values[(unsigned char)str[24]];
      case 24:
        hval += asso_values[(unsigned char)str[23]];
      case 23:
        hval += asso_values[(unsigned char)str[22]];
      case 22:
        hval += asso_values[(unsigned char)str[21]];
      case 21:
        hval += asso_values[(unsigned char)str[20]];
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      case 19:
        hval += asso_values[(unsigned char)str[18]];
      case 18:
        hval += asso_values[(unsigned char)str[17]];
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      case 16:
        hval += asso_values[(unsigned char)str[15]];
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

#ifdef __GNUC__
__inline
#endif
struct resword *
in_word_set (str, len)
     register const char *str;
     register unsigned int len;
{
  enum
    {
      TOTAL_KEYWORDS = 300,
      MIN_WORD_LENGTH = 2,
      MAX_WORD_LENGTH = 30,
      MIN_HASH_VALUE = 40,
      MAX_HASH_VALUE = 2691
    };

  static struct resword wordlist[] =
    {
      {"seize",			SEIZE,			NORID,	RESERVED},
      {"page",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"SEIZE",			SEIZE,			NORID,	RESERVED},
      {"case",			CASE,			NORID,	RESERVED},
      {"esac",			ESAC,			NORID,	RESERVED},
      {"ELSE",			ELSE,			NORID,	RESERVED},
      {"asm",			ASM_KEYWORD,		NORID,	RESERVED},
      {"WHILE",			WHILE,			NORID,	RESERVED},
      {"spec",			SPEC,			NORID,	RESERVED},
      {"EVER",			EVER,			NORID,	RESERVED},
      {"pack",			PACK,			NORID,	RESERVED},
      {"fi",			FI,			NORID,	RESERVED},
      {"if",			IF,			NORID,	RESERVED},
      {"access",			ACCESS,			NORID,	RESERVED},
      {"up",			UP,			NORID,	RESERVED},
      {"ever",			EVER,			NORID,	RESERVED},
      {"UP",			UP,			NORID,	RESERVED},
      {"cause",			CAUSE,			NORID,	RESERVED},
      {"SPEC",			SPEC,			NORID,	RESERVED},
      {"BY",			BY,			NORID,	RESERVED},
      {"else",			ELSE,			NORID,	RESERVED},
      {"OR",			OR,			NORID,	RESERVED},
      {"by",			BY,			NORID,	RESERVED},
      {"ROW",			ROW,			NORID,	RESERVED},
      {"XOR",			XOR,			NORID,	RESERVED},
      {"POS",			POS,			NORID,	RESERVED},
      {"receive",		RECEIVE,		NORID,	RESERVED},
      {"rem",			REM,			NORID,	RESERVED},
      {"while",			WHILE,			NORID,	RESERVED},
      {"RECEIVE",		RECEIVE,		NORID,	RESERVED},
      {"chars",			CHARS,			NORID,	RESERVED},
      {"LOC",			LOC,			NORID,	RESERVED},
      {"based",			BASED,			NORID,	RESERVED},
      {"EVEN",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ref",			REF,			NORID,	RESERVED},
      {"IN",			IN,			RID_IN,	RESERVED},
      {"DO",			DO,			NORID,	RESERVED},
      {"OD",			OD,			NORID,	RESERVED},
      {"far",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"CYCLE",			CYCLE,			NORID,	RESERVED},
      {"read",			READ,			RID_READ,	RESERVED},
      {"DCL",			DCL,			NORID,	RESERVED},
      {"CASE",			CASE,			NORID,	RESERVED},
      {"ESAC",			ESAC,			NORID,	RESERVED},
      {"PAGE",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"elsif",			ELSIF,			NORID,	RESERVED},
      {"SYN",			SYN,			NORID,	RESERVED},
      {"simple",			SIMPLE,			NORID,	RESERVED},
      {"ON",			ON,			NORID,	RESERVED},
      {"large",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ALL",			ALL,			NORID,	RESERVED},
      {"FI",			FI,			NORID,	RESERVED},
      {"IF",			IF,			NORID,	RESERVED},
      {"set",			SET,			NORID,	RESERVED},
      {"PROC",			PROC,			NORID,	RESERVED},
      {"at",			AT,			NORID,	RESERVED},
      {"CAUSE",			CAUSE,			NORID,	RESERVED},
      {"exit",			EXIT,			NORID,	RESERVED},
      {"all",			ALL,			NORID,	RESERVED},
      {"BIN",			BIN,			NORID,	RESERVED},
      {"dcl",			DCL,			NORID,	RESERVED},
      {"PACK",			PACK,			NORID,	RESERVED},
      {"BEGIN",			BEGINTOKEN,		NORID,	RESERVED},
      {"LARGE",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ACCESS",			ACCESS,			NORID,	RESERVED},
      {"this",			THIS,			NORID,	RESERVED},
      {"with",			WITH,			NORID,	RESERVED},
      {"END",			END,			NORID,	RESERVED},
      {"REM",			REM,			NORID,	RESERVED},
      {"PROCESS",		PROCESS,		NORID,	RESERVED},
      {"CHARS",			CHARS,			NORID,	RESERVED},
      {"BOOLS",			BOOLS,			RID_BOOLS,	RESERVED},
      {"pos",			POS,			NORID,	RESERVED},
      {"RECURSIVE",		RECURSIVE,		NORID,	RESERVED},
      {"medium",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"step",			STEP,			NORID,	RESERVED},
      {"SEND",			SEND,			NORID,	RESERVED},
      {"CALL",			CALL,			NORID,	RESERVED},
      {"REF",			REF,			NORID,	RESERVED},
      {"OF",			OF,			NORID,	RESERVED},
      {"cycle",			CYCLE,			NORID,	RESERVED},
      {"array",			ARRAY,			NORID,	RESERVED},
      {"call",			CALL,			NORID,	RESERVED},
      {"ELSIF",			ELSIF,			NORID,	RESERVED},
      {"bit",			BOOLS,			RID_BOOLS,	PREDEF},
      {"BODY",			BODY,			NORID,	RESERVED},
      {"recursive",		RECURSIVE,		NORID,	RESERVED},
      {"small",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"delay",			DELAY,			NORID,	RESERVED},
      {"of",			OF,			NORID,	RESERVED},
      {"REGION",			REGION,			NORID,	RESERVED},
      {"prefixed",		PREFIXED,		NORID,	RESERVED},
      {"READ",			READ,			RID_READ,	RESERVED},
      {"use_seize_file",		USE_SEIZE_FILE,		NORID,	DIRECTIVE},
      {"or",			OR,			NORID,	RESERVED},
      {"do",			DO,			NORID,	RESERVED},
      {"od",			OD,			NORID,	RESERVED},
      {"xor",			XOR,			NORID,	RESERVED},
      {"row",			ROW,			NORID,	RESERVED},
      {"DOWN",			DOWN,			NORID,	RESERVED},
      {"SIMPLE",			SIMPLE,			NORID,	RESERVED},
      {"BASED",			BASED,			NORID,	RESERVED},
      {"assert",			ASSERT,			NORID,	RESERVED},
      {"FOR",			FOR,			NORID,	RESERVED},
      {"DELAY",			DELAY,			NORID,	RESERVED},
      {"ASM",			ASM_KEYWORD,		NORID,	RESERVED},
      {"even",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"in",			IN,			RID_IN,	RESERVED},
      {"RANGE",			RANGE,			NORID,	RESERVED},
      {"list",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ORIF",			ORIF,			NORID,	RESERVED},
      {"buffer",			BUFFER,			NORID,	RESERVED},
      {"MOD",			MOD,			NORID,	RESERVED},
      {"SIGNAL",			SIGNAL,			NORID,	RESERVED},
      {"mod",			MOD,			NORID,	RESERVED},
      {"USE_SEIZE_FILE",		USE_SEIZE_FILE,		NORID,	DIRECTIVE},
      {"loc",			LOC,			NORID,	RESERVED},
      {"INLINE",			INLINE,			RID_INLINE,	RESERVED},
      {"proc",			PROC,			NORID,	RESERVED},
      {"AND",			AND,			NORID,	RESERVED},
      {"process",		PROCESS,		NORID,	RESERVED},
      {"for",			FOR,			NORID,	RESERVED},
      {"bin",			BIN,			NORID,	RESERVED},
      {"GENERAL",		GENERAL,		NORID,	RESERVED},
      {"begin",			BEGINTOKEN,		NORID,	RESERVED},
      {"orif",			ORIF,			NORID,	RESERVED},
      {"after",			AFTER,			NORID,	RESERVED},
      {"FAR",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"syn",			SYN,			NORID,	RESERVED},
      {"SMALL",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"end",			END,			NORID,	RESERVED},
      {"send",			SEND,			NORID,	RESERVED},
      {"VARYING",		VARYING,		NORID,	RESERVED},
      {"and",			AND,			NORID,	RESERVED},
      {"range",			RANGE,			NORID,	RESERVED},
      {"body",			BODY,			NORID,	RESERVED},
      {"MODULE",			MODULE,			NORID,	RESERVED},
      {"ARRAY",			ARRAY,			NORID,	RESERVED},
      {"DEBUG_LINES",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"to",			TO,			NORID,	RESERVED},
      {"SET",			SET,			NORID,	RESERVED},
      {"text",			TEXT,			NORID,	RESERVED},
      {"NOPACK",			NOPACK,			NORID,	RESERVED},
      {"PREFIXED",		PREFIXED,		NORID,	RESERVED},
      {"WITH",			WITH,			NORID,	RESERVED},
      {"EXIT",			EXIT,			NORID,	RESERVED},
      {"signal",			SIGNAL,			NORID,	RESERVED},
      {"THIS",			THIS,			NORID,	RESERVED},
      {"stop",			STOP,			NORID,	RESERVED},
      {"result",			RESULT,			NORID,	RESERVED},
      {"TO",			TO,			NORID,	RESERVED},
      {"static",			STATIC,			NORID,	RESERVED},
      {"out",			PARAMATTR,		RID_OUT,	RESERVED},
      {"STEP",			STEP,			NORID,	RESERVED},
      {"NEWMODE",		NEWMODE,		NORID,	RESERVED},
      {"LIST",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"andif",			ANDIF,			NORID,	RESERVED},
      {"varying",		VARYING,		NORID,	RESERVED},
      {"FORBID",			FORBID,			NORID,	RESERVED},
      {"BIT",			BOOLS,			RID_BOOLS,	PREDEF},
      {"forbid",			FORBID,			NORID,	RESERVED},
      {"module",			MODULE,			NORID,	RESERVED},
      {"OUT",			PARAMATTR,		RID_OUT,	RESERVED},
      {"debug_types",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"MEDIUM",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"start",			START,			NORID,	RESERVED},
      {"general",		GENERAL,		NORID,	RESERVED},
      {"on",			ON,			NORID,	RESERVED},
      {"RANGE_ON",		RANGE_ON,		NORID,	DIRECTIVE},
      {"event",			EVENT,			NORID,	RESERVED},
      {"SYNMODE",		SYNMODE,		NORID,	RESERVED},
      {"GOTO",			GOTO,			NORID,	RESERVED},
      {"STOP",			STOP,			NORID,	RESERVED},
      {"AT",			AT,			NORID,	RESERVED},
      {"init",			INIT,			NORID,	RESERVED},
      {"optimize",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"then",			THEN,			NORID,	RESERVED},
      {"SIGNAL_CODE",		SIGNAL_CODE,		NORID,	DIRECTIVE},
      {"powerset",		POWERSET,		NORID,	RESERVED},
      {"BUFFER",			BUFFER,			NORID,	RESERVED},
      {"THEN",			THEN,			NORID,	RESERVED},
      {"remote",			REMOTE,			NORID,	RESERVED},
      {"RESULT",			RESULT,			NORID,	RESERVED},
      {"EVENT",			EVENT,			NORID,	RESERVED},
      {"dynamic",		DYNAMIC,		RID_DYNAMIC,	RESERVED},
      {"ANDIF",			ANDIF,			NORID,	RESERVED},
      {"bools",			BOOLS,			RID_BOOLS,	RESERVED},
      {"NONREF",			NONREF,			NORID,	RESERVED},
      {"INIT",			INIT,			NORID,	RESERVED},
      {"nopack",			NOPACK,			NORID,	RESERVED},
      {"struct",			STRUCT,			NORID,	RESERVED},
      {"POWERSET",		POWERSET,		NORID,	RESERVED},
      {"NOT",			NOT,			NORID,	RESERVED},
      {"down",			DOWN,			NORID,	RESERVED},
      {"grant",			GRANT,			NORID,	RESERVED},
      {"region",			REGION,			NORID,	RESERVED},
      {"ASSERT",			ASSERT,			NORID,	RESERVED},
      {"DEBUG_SYMBOLS",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"debug_lines",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"goto",			GOTO,			NORID,	RESERVED},
      {"DYNAMIC",		DYNAMIC,		RID_DYNAMIC,	RESERVED},
      {"NO_OVERLAP_CHECK",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"newmode",		NEWMODE,		NORID,	RESERVED},
      {"buffer_code",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"INOUT",			PARAMATTR,		RID_INOUT,	RESERVED},
      {"NOLIST",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"process_type",		PROCESS_TYPE_TOKEN,	NORID,	DIRECTIVE},
      {"debug_symbols",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"RETURN",			RETURN,			NORID,	RESERVED},
      {"priority",		PRIORITY,		NORID,	RESERVED},
      {"REMOTE",			REMOTE,			NORID,	RESERVED},
      {"ccitt_os",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"RETURNS",		RETURNS,		NORID,	RESERVED},
      {"empty_off",		EMPTY_OFF,		NORID,	DIRECTIVE},
      {"PRIORITY",		PRIORITY,		NORID,	RESERVED},
      {"DEBUG_TYPES",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"synmode",		SYNMODE,		NORID,	RESERVED},
      {"not",			NOT,			NORID,	RESERVED},
      {"GRANT",			GRANT,			NORID,	RESERVED},
      {"EXCEPTIONS",		EXCEPTIONS,		NORID,	RESERVED},
      {"timeout",		TIMEOUT,		NORID,	RESERVED},
      {"BUFFER_CODE",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"return",			RETURN,			NORID,	RESERVED},
      {"inline",			INLINE,			RID_INLINE,	RESERVED},
      {"returns",		RETURNS,		NORID,	RESERVED},
      {"PROCESS_TYPE",		PROCESS_TYPE_TOKEN,	NORID,	DIRECTIVE},
      {"OPTIMIZE",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"range_off",		RANGE_OFF,		NORID,	DIRECTIVE},
      {"EVENT_CODE",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"RANGE_OFF",		RANGE_OFF,		NORID,	DIRECTIVE},
      {"signal_code",		SIGNAL_CODE,		NORID,	DIRECTIVE},
      {"AFTER",			AFTER,			NORID,	RESERVED},
      {"inout",			PARAMATTR,		RID_INOUT,	RESERVED},
      {"exceptions",		EXCEPTIONS,		NORID,	RESERVED},
      {"TEXT",			TEXT,			NORID,	RESERVED},
      {"grant_file_size",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"CONTINUE",		CONTINUE,		NORID,	RESERVED},
      {"nolist",			IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"short_pred_succ",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"event_code",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"EMPTY_ON",		EMPTY_ON,		NORID,	DIRECTIVE},
      {"empty_on",		EMPTY_ON,		NORID,	DIRECTIVE},
      {"SHORT_PRED_SUCC",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"multiple_data_segs",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"range_on",		RANGE_ON,		NORID,	DIRECTIVE},
      {"PRINT_O_CODE",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"STRUCT",			STRUCT,			NORID,	RESERVED},
      {"context",		CONTEXT,		NORID,	RESERVED},
      {"nonref",			NONREF,			NORID,	RESERVED},
      {"CCITT_OS",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"use_seize_file_restricted",	USE_SEIZE_FILE_RESTRICTED,	NORID,	DIRECTIVE},
      {"START",			START,			NORID,	RESERVED},
      {"STATIC",			STATIC,			NORID,	RESERVED},
      {"GRANT_FILE_SIZE",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"all_static_off",		ALL_STATIC_OFF,		NORID,  DIRECTIVE},
      {"no_overlap_check",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"CONTEXT",		CONTEXT,		NORID,	RESERVED},
      {"extra_const_seg",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"TIMEOUT",		TIMEOUT,		NORID,	RESERVED},
      {"EMPTY_OFF",		EMPTY_OFF,		NORID,	DIRECTIVE},
      {"continue",		CONTINUE,		NORID,	RESERVED},
      {"signal_max_length",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"print_o_code",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"generate_set_names",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"all_static_on",		ALL_STATIC_ON,		NORID,	DIRECTIVE},
      {"reentrant",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"SIGNAL_MAX_LENGTH",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"optimize_runtime",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"EXTRA_CONST_SEG",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"support_causing_address",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"state_routine",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"REENTRANT",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"multiple_const_segs",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ALL_STATIC_ON",		ALL_STATIC_ON,		NORID,	DIRECTIVE},
      {"generate_all_set_names",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"reentrant_all",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"USE_SEIZE_FILE_RESTRICTED",	USE_SEIZE_FILE_RESTRICTED,	NORID,	DIRECTIVE},
      {"MULTIPLE_CONST_SEGS",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"SUPPORT_CAUSING_ADDRESS",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"print_symbol_table",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"make_publics_for_discrete_syns",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"REENTRANT_ALL",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"MULTIPLE_DATA_SEGS",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"only_for_target",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"OPTIMIZE_RUNTIME",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ONLY_FOR_TARGET",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"GENERATE_SET_NAMES",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ONLY_FOR_SIMULATION",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"ALL_STATIC_OFF",		ALL_STATIC_OFF,		NORID,  DIRECTIVE},
      {"STATE_ROUTINE",		IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"PRINT_SYMBOL_TABLE",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"MAKE_PUBLICS_FOR_DISCRETE_SYNS",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"GENERATE_ALL_SET_NAMES",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"OPTIMIZATION_WINDOW",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"optimization_window",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"send_buffer_default_priority",	SEND_BUFFER_DEFAULT_PRIORITY,	NORID,	DIRECTIVE},
      {"only_for_simulation",	IGNORED_DIRECTIVE,	NORID,	DIRECTIVE},
      {"send_signal_default_priority",	SEND_SIGNAL_DEFAULT_PRIORITY,	NORID,	DIRECTIVE},
      {"SEND_SIGNAL_DEFAULT_PRIORITY",	SEND_SIGNAL_DEFAULT_PRIORITY,	NORID,	DIRECTIVE},
      {"SEND_BUFFER_DEFAULT_PRIORITY",	SEND_BUFFER_DEFAULT_PRIORITY,	NORID,	DIRECTIVE}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          register struct resword *wordptr;
          register struct resword *wordendptr;
          register struct resword *resword;

          switch (key - 40)
            {
              case 0:
                resword = &wordlist[0];
                goto compare;
              case 5:
                resword = &wordlist[1];
                goto compare;
              case 8:
                resword = &wordlist[2];
                goto compare;
              case 9:
                wordptr = &wordlist[3];
                wordendptr = wordptr + 2;
                goto multicompare;
              case 20:
                resword = &wordlist[5];
                goto compare;
              case 22:
                resword = &wordlist[6];
                goto compare;
              case 34:
                resword = &wordlist[7];
                goto compare;
              case 36:
                resword = &wordlist[8];
                goto compare;
              case 41:
                resword = &wordlist[9];
                goto compare;
              case 42:
                resword = &wordlist[10];
                goto compare;
              case 47:
                wordptr = &wordlist[11];
                wordendptr = wordptr + 2;
                goto multicompare;
              case 49:
                resword = &wordlist[13];
                goto compare;
              case 55:
                resword = &wordlist[14];
                goto compare;
              case 59:
                resword = &wordlist[15];
                goto compare;
              case 64:
                resword = &wordlist[16];
                goto compare;
              case 70:
                resword = &wordlist[17];
                goto compare;
              case 80:
                resword = &wordlist[18];
                goto compare;
              case 84:
                resword = &wordlist[19];
                goto compare;
              case 86:
                resword = &wordlist[20];
                goto compare;
              case 93:
                resword = &wordlist[21];
                goto compare;
              case 94:
                resword = &wordlist[22];
                goto compare;
              case 96:
                resword = &wordlist[23];
                goto compare;
              case 97:
                resword = &wordlist[24];
                goto compare;
              case 101:
                resword = &wordlist[25];
                goto compare;
              case 107:
                resword = &wordlist[26];
                goto compare;
              case 108:
                resword = &wordlist[27];
                goto compare;
              case 109:
                resword = &wordlist[28];
                goto compare;
              case 111:
                resword = &wordlist[29];
                goto compare;
              case 116:
                resword = &wordlist[30];
                goto compare;
              case 117:
                resword = &wordlist[31];
                goto compare;
              case 118:
                resword = &wordlist[32];
                goto compare;
              case 128:
                resword = &wordlist[33];
                goto compare;
              case 134:
                resword = &wordlist[34];
                goto compare;
              case 135:
                resword = &wordlist[35];
                goto compare;
              case 136:
                wordptr = &wordlist[36];
                wordendptr = wordptr + 2;
                goto multicompare;
              case 139:
                resword = &wordlist[38];
                goto compare;
              case 145:
                resword = &wordlist[39];
                goto compare;
              case 156:
                resword = &wordlist[40];
                goto compare;
              case 157:
                resword = &wordlist[41];
                goto compare;
              case 161:
                wordptr = &wordlist[42];
                wordendptr = wordptr + 2;
                goto multicompare;
              case 167:
                resword = &wordlist[44];
                goto compare;
              case 171:
                resword = &wordlist[45];
                goto compare;
              case 173:
                resword = &wordlist[46];
                goto compare;
              case 179:
                resword = &wordlist[47];
                goto compare;
              case 180:
                resword = &wordlist[48];
                goto compare;
              case 184:
                resword = &wordlist[49];
                goto compare;
              case 190:
                resword = &wordlist[50];
                goto compare;
              case 192:
                wordptr = &wordlist[51];
                wordendptr = wordptr + 2;
                goto multicompare;
              case 198:
                resword = &wordlist[53];
                goto compare;
              case 199:
                resword = &wordlist[54];
                goto compare;
              case 201:
                resword = &wordlist[55];
                goto compare;
              case 204:
                resword = &wordlist[56];
                goto compare;
              case 206:
                resword = &wordlist[57];
                goto compare;
              case 207:
                resword = &wordlist[58];
                goto compare;
              case 210:
                resword = &wordlist[59];
                goto compare;
              case 212:
                resword = &wordlist[60];
                goto compare;
              case 213:
                resword = &wordlist[61];
                goto compare;
              case 214:
                resword = &wordlist[62];
                goto compare;
              case 215:
                resword = &wordlist[63];
                goto compare;
              case 218:
                resword = &wordlist[64];
                goto compare;
              case 220:
                resword = &wordlist[65];
                goto compare;
              case 221:
                resword = &wordlist[66];
                goto compare;
              case 222:
                resword = &wordlist[67];
                goto compare;
              case 223:
                resword = &wordlist[68];
                goto compare;
              case 225:
                resword = &wordlist[69];
                goto compare;
              case 226:
                resword = &wordlist[70];
                goto compare;
              case 227:
                resword = &wordlist[71];
                goto compare;
              case 228:
                resword = &wordlist[72];
                goto compare;
              case 229:
                resword = &wordlist[73];
                goto compare;
              case 231:
                resword = &wordlist[74];
                goto compare;
              case 232:
                resword = &wordlist[75];
                goto compare;
              case 234:
                resword = &wordlist[76];
                goto compare;
              case 235:
                resword = &wordlist[77];
                goto compare;
              case 236:
                resword = &wordlist[78];
                goto compare;
              case 237:
                resword = &wordlist[79];
                goto compare;
              case 239:
                resword = &wordlist[80];
                goto compare;
              case 241:
                resword = &wordlist[81];
                goto compare;
              case 245:
                resword = &wordlist[82];
                goto compare;
              case 250:
                resword = &wordlist[83];
                goto compare;
              case 255:
                resword = &wordlist[84];
                goto compare;
              case 260:
                resword = &wordlist[85];
                goto compare;
              case 261:
                resword = &wordlist[86];
                goto compare;
              case 262:
                resword = &wordlist[87];
                goto compare;
              case 264:
                resword = &wordlist[88];
                goto compare;
              case 271:
                resword = &wordlist[89];
                goto compare;
              case 272:
                resword = &wordlist[90];
                goto compare;
              case 274:
                resword = &wordlist[91];
                goto compare;
              case 277:
                resword = &wordlist[92];
                goto compare;
              case 278:
                resword = &wordlist[93];
                goto compare;
              case 285:
                resword = &wordlist[94];
                goto compare;
              case 286:
                wordptr = &wordlist[95];
                wordendptr = wordptr + 2;
                goto multicompare;
              case 287:
                resword = &wordlist[97];
                goto compare;
              case 288:
                resword = &wordlist[98];
                goto compare;
              case 291:
                resword = &wordlist[99];
                goto compare;
              case 298:
                resword = &wordlist[100];
                goto compare;
              case 299:
                resword = &wordlist[101];
                goto compare;
              case 300:
                resword = &wordlist[102];
                goto compare;
              case 302:
                resword = &wordlist[103];
                goto compare;
              case 305:
                resword = &wordlist[104];
                goto compare;
              case 310:
                resword = &wordlist[105];
                goto compare;
              case 312:
                resword = &wordlist[106];
                goto compare;
              case 314:
                resword = &wordlist[107];
                goto compare;
              case 323:
                resword = &wordlist[108];
                goto compare;
              case 324:
                resword = &wordlist[109];
                goto compare;
              case 325:
                resword = &wordlist[110];
                goto compare;
              case 327:
                resword = &wordlist[111];
                goto compare;
              case 332:
                resword = &wordlist[112];
                goto compare;
              case 335:
                resword = &wordlist[113];
                goto compare;
              case 339:
                resword = &wordlist[114];
                goto compare;
              case 347:
                resword = &wordlist[115];
                goto compare;
              case 350:
                resword = &wordlist[116];
                goto compare;
              case 356:
                resword = &wordlist[117];
                goto compare;
              case 357:
                resword = &wordlist[118];
                goto compare;
              case 362:
                resword = &wordlist[119];
                goto compare;
              case 363:
                resword = &wordlist[120];
                goto compare;
              case 364:
                resword = &wordlist[121];
                goto compare;
              case 367:
                resword = &wordlist[122];
                goto compare;
              case 369:
                resword = &wordlist[123];
                goto compare;
              case 371:
                resword = &wordlist[124];
                goto compare;
              case 372:
                resword = &wordlist[125];
                goto compare;
              case 375:
                resword = &wordlist[126];
                goto compare;
              case 376:
                resword = &wordlist[127];
                goto compare;
              case 389:
                resword = &wordlist[128];
                goto compare;
              case 398:
                resword = &wordlist[129];
                goto compare;
              case 402:
                resword = &wordlist[130];
                goto compare;
              case 404:
                resword = &wordlist[131];
                goto compare;
              case 405:
                resword = &wordlist[132];
                goto compare;
              case 407:
                resword = &wordlist[133];
                goto compare;
              case 410:
                resword = &wordlist[134];
                goto compare;
              case 420:
                resword = &wordlist[135];
                goto compare;
              case 421:
                resword = &wordlist[136];
                goto compare;
              case 423:
                resword = &wordlist[137];
                goto compare;
              case 425:
                resword = &wordlist[138];
                goto compare;
              case 426:
                resword = &wordlist[139];
                goto compare;
              case 427:
                resword = &wordlist[140];
                goto compare;
              case 432:
                resword = &wordlist[141];
                goto compare;
              case 433:
                resword = &wordlist[142];
                goto compare;
              case 434:
                resword = &wordlist[143];
                goto compare;
              case 441:
                resword = &wordlist[144];
                goto compare;
              case 442:
                resword = &wordlist[145];
                goto compare;
              case 445:
                resword = &wordlist[146];
                goto compare;
              case 450:
                resword = &wordlist[147];
                goto compare;
              case 462:
                resword = &wordlist[148];
                goto compare;
              case 472:
                resword = &wordlist[149];
                goto compare;
              case 481:
                resword = &wordlist[150];
                goto compare;
              case 483:
                resword = &wordlist[151];
                goto compare;
              case 487:
                resword = &wordlist[152];
                goto compare;
              case 488:
                resword = &wordlist[153];
                goto compare;
              case 491:
                resword = &wordlist[154];
                goto compare;
              case 492:
                resword = &wordlist[155];
                goto compare;
              case 494:
                resword = &wordlist[156];
                goto compare;
              case 499:
                resword = &wordlist[157];
                goto compare;
              case 508:
                resword = &wordlist[158];
                goto compare;
              case 511:
                resword = &wordlist[159];
                goto compare;
              case 519:
                resword = &wordlist[160];
                goto compare;
              case 522:
                resword = &wordlist[161];
                goto compare;
              case 524:
                resword = &wordlist[162];
                goto compare;
              case 527:
                resword = &wordlist[163];
                goto compare;
              case 528:
                resword = &wordlist[164];
                goto compare;
              case 530:
                resword = &wordlist[165];
                goto compare;
              case 532:
                resword = &wordlist[166];
                goto compare;
              case 538:
                resword = &wordlist[167];
                goto compare;
              case 545:
                resword = &wordlist[168];
                goto compare;
              case 546:
                resword = &wordlist[169];
                goto compare;
              case 547:
                resword = &wordlist[170];
                goto compare;
              case 551:
                resword = &wordlist[171];
                goto compare;
              case 554:
                resword = &wordlist[172];
                goto compare;
              case 555:
                resword = &wordlist[173];
                goto compare;
              case 556:
                resword = &wordlist[174];
                goto compare;
              case 557:
                resword = &wordlist[175];
                goto compare;
              case 558:
                resword = &wordlist[176];
                goto compare;
              case 560:
                resword = &wordlist[177];
                goto compare;
              case 562:
                resword = &wordlist[178];
                goto compare;
              case 563:
                resword = &wordlist[179];
                goto compare;
              case 569:
                resword = &wordlist[180];
                goto compare;
              case 576:
                resword = &wordlist[181];
                goto compare;
              case 579:
                resword = &wordlist[182];
                goto compare;
              case 581:
                resword = &wordlist[183];
                goto compare;
              case 587:
                resword = &wordlist[184];
                goto compare;
              case 594:
                resword = &wordlist[185];
                goto compare;
              case 599:
                resword = &wordlist[186];
                goto compare;
              case 608:
                resword = &wordlist[187];
                goto compare;
              case 611:
                resword = &wordlist[188];
                goto compare;
              case 620:
                resword = &wordlist[189];
                goto compare;
              case 622:
                resword = &wordlist[190];
                goto compare;
              case 626:
                resword = &wordlist[191];
                goto compare;
              case 633:
                resword = &wordlist[192];
                goto compare;
              case 635:
                resword = &wordlist[193];
                goto compare;
              case 642:
                resword = &wordlist[194];
                goto compare;
              case 643:
                resword = &wordlist[195];
                goto compare;
              case 646:
                resword = &wordlist[196];
                goto compare;
              case 648:
                resword = &wordlist[197];
                goto compare;
              case 652:
                resword = &wordlist[198];
                goto compare;
              case 660:
                resword = &wordlist[199];
                goto compare;
              case 675:
                resword = &wordlist[200];
                goto compare;
              case 677:
                resword = &wordlist[201];
                goto compare;
              case 692:
                resword = &wordlist[202];
                goto compare;
              case 695:
                resword = &wordlist[203];
                goto compare;
              case 699:
                resword = &wordlist[204];
                goto compare;
              case 712:
                resword = &wordlist[205];
                goto compare;
              case 716:
                resword = &wordlist[206];
                goto compare;
              case 717:
                resword = &wordlist[207];
                goto compare;
              case 740:
                resword = &wordlist[208];
                goto compare;
              case 743:
                resword = &wordlist[209];
                goto compare;
              case 746:
                resword = &wordlist[210];
                goto compare;
              case 748:
                resword = &wordlist[211];
                goto compare;
              case 752:
                resword = &wordlist[212];
                goto compare;
              case 756:
                resword = &wordlist[213];
                goto compare;
              case 767:
                resword = &wordlist[214];
                goto compare;
              case 769:
                resword = &wordlist[215];
                goto compare;
              case 770:
                resword = &wordlist[216];
                goto compare;
              case 772:
                resword = &wordlist[217];
                goto compare;
              case 774:
                resword = &wordlist[218];
                goto compare;
              case 782:
                resword = &wordlist[219];
                goto compare;
              case 784:
                resword = &wordlist[220];
                goto compare;
              case 788:
                resword = &wordlist[221];
                goto compare;
              case 789:
                resword = &wordlist[222];
                goto compare;
              case 790:
                resword = &wordlist[223];
                goto compare;
              case 791:
                resword = &wordlist[224];
                goto compare;
              case 792:
                resword = &wordlist[225];
                goto compare;
              case 795:
                resword = &wordlist[226];
                goto compare;
              case 802:
                resword = &wordlist[227];
                goto compare;
              case 806:
                resword = &wordlist[228];
                goto compare;
              case 811:
                resword = &wordlist[229];
                goto compare;
              case 813:
                resword = &wordlist[230];
                goto compare;
              case 831:
                resword = &wordlist[231];
                goto compare;
              case 841:
                resword = &wordlist[232];
                goto compare;
              case 860:
                resword = &wordlist[233];
                goto compare;
              case 872:
                resword = &wordlist[234];
                goto compare;
              case 893:
                resword = &wordlist[235];
                goto compare;
              case 898:
                resword = &wordlist[236];
                goto compare;
              case 902:
                resword = &wordlist[237];
                goto compare;
              case 903:
                resword = &wordlist[238];
                goto compare;
              case 914:
                resword = &wordlist[239];
                goto compare;
              case 943:
                resword = &wordlist[240];
                goto compare;
              case 944:
                resword = &wordlist[241];
                goto compare;
              case 945:
                resword = &wordlist[242];
                goto compare;
              case 946:
                resword = &wordlist[243];
                goto compare;
              case 990:
                resword = &wordlist[244];
                goto compare;
              case 1009:
                resword = &wordlist[245];
                goto compare;
              case 1031:
                resword = &wordlist[246];
                goto compare;
              case 1048:
                resword = &wordlist[247];
                goto compare;
              case 1058:
                resword = &wordlist[248];
                goto compare;
              case 1061:
                resword = &wordlist[249];
                goto compare;
              case 1080:
                resword = &wordlist[250];
                goto compare;
              case 1085:
                resword = &wordlist[251];
                goto compare;
              case 1088:
                resword = &wordlist[252];
                goto compare;
              case 1102:
                resword = &wordlist[253];
                goto compare;
              case 1124:
                resword = &wordlist[254];
                goto compare;
              case 1129:
                resword = &wordlist[255];
                goto compare;
              case 1137:
                resword = &wordlist[256];
                goto compare;
              case 1160:
                resword = &wordlist[257];
                goto compare;
              case 1198:
                resword = &wordlist[258];
                goto compare;
              case 1209:
                resword = &wordlist[259];
                goto compare;
              case 1227:
                resword = &wordlist[260];
                goto compare;
              case 1231:
                resword = &wordlist[261];
                goto compare;
              case 1277:
                resword = &wordlist[262];
                goto compare;
              case 1300:
                resword = &wordlist[263];
                goto compare;
              case 1312:
                resword = &wordlist[264];
                goto compare;
              case 1317:
                resword = &wordlist[265];
                goto compare;
              case 1336:
                resword = &wordlist[266];
                goto compare;
              case 1356:
                resword = &wordlist[267];
                goto compare;
              case 1376:
                resword = &wordlist[268];
                goto compare;
              case 1412:
                resword = &wordlist[269];
                goto compare;
              case 1417:
                resword = &wordlist[270];
                goto compare;
              case 1446:
                resword = &wordlist[271];
                goto compare;
              case 1456:
                resword = &wordlist[272];
                goto compare;
              case 1542:
                resword = &wordlist[273];
                goto compare;
              case 1549:
                resword = &wordlist[274];
                goto compare;
              case 1566:
                resword = &wordlist[275];
                goto compare;
              case 1577:
                resword = &wordlist[276];
                goto compare;
              case 1588:
                resword = &wordlist[277];
                goto compare;
              case 1595:
                resword = &wordlist[278];
                goto compare;
              case 1636:
                resword = &wordlist[279];
                goto compare;
              case 1657:
                resword = &wordlist[280];
                goto compare;
              case 1678:
                resword = &wordlist[281];
                goto compare;
              case 1703:
                resword = &wordlist[282];
                goto compare;
              case 1719:
                resword = &wordlist[283];
                goto compare;
              case 1731:
                resword = &wordlist[284];
                goto compare;
              case 1736:
                resword = &wordlist[285];
                goto compare;
              case 1755:
                resword = &wordlist[286];
                goto compare;
              case 1775:
                resword = &wordlist[287];
                goto compare;
              case 1808:
                resword = &wordlist[288];
                goto compare;
              case 1830:
                resword = &wordlist[289];
                goto compare;
              case 1878:
                resword = &wordlist[290];
                goto compare;
              case 1893:
                resword = &wordlist[291];
                goto compare;
              case 1987:
                resword = &wordlist[292];
                goto compare;
              case 1990:
                resword = &wordlist[293];
                goto compare;
              case 2070:
                resword = &wordlist[294];
                goto compare;
              case 2157:
                resword = &wordlist[295];
                goto compare;
              case 2218:
                resword = &wordlist[296];
                goto compare;
              case 2275:
                resword = &wordlist[297];
                goto compare;
              case 2423:
                resword = &wordlist[298];
                goto compare;
              case 2651:
                resword = &wordlist[299];
                goto compare;
            }
          return 0;
        multicompare:
          while (wordptr < wordendptr)
            {
              register const char *s = wordptr->name;

              if (*str == *s && !strcmp (str + 1, s + 1))
                return wordptr;
              wordptr++;
            }
          return 0;
        compare:
          {
            register const char *s = resword->name;

            if (*str == *s && !strcmp (str + 1, s + 1))
              return resword;
          }
        }
    }
  return 0;
}
